version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: rooming-list-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: rooming_list_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - rooming-list-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rooming_list_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rooming-list-app
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_DATABASE_URL=postgresql://postgres:password123@postgres:5432/rooming_list_db
      - VITE_APP_URL=http://localhost:5173
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - rooming-list-network
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rooming-list-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - rooming-list-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  rooming-list-network:
    driver: bridge
